### ISSUE TITLE
Eklenecek SQL sorguları

### ISSUE THREAD

**Issue by bayraktugrul** [tgrlbyrk/vuejs-movie-db-project#1]
1- En son 5 haberin verileri tablodan çekilecek ( ana sayfa için )
2- En çok okunan 5 haberin verileri tablodan çekilecek ( ana sayfa için ) 
3- Haberler sayfası için haberlerin tamamı tarih sıralamasına göre çekilecek 
4- Kategori farketmeksizin filmler  & diziler (ayrı ayrı) imdb puanlarına göre sıralanacak 
5- Belirli bir kategorideki  filmler &diziler (ayrı ayrı) imdb puanlarına göre sıralanacak
6- Kullanıcıların tamamının listesi çekilebilecek (admin paneli için) 
7- Belirli bir film ve dizi için tüm yorumlar tarih sırasına göre çekilecek
8- Kullanıcı profili için belli kullanıcıya ait favori film ve diziler ayrı ayrı çekilecek. (Favori diziler & Favori filmler) 

Bu işlemlerin SQL sorguları yazılacak. 

Not: Insert işlemleri için SQL sorguları daha sonra yazılacak.

**Comment by rsafaraliyeva** [comment]
1)   SELECT * FROM News ORDER BY news_date DESC LIMIT 5
2)  SELECT * FROM News ORDER BY news_views DESC LIMIT 5
3)  SELECT * FROM News ORDER BY news_date DESC
4)  SELECT * FROM Movies ORDER BY movie_imdb DESC
5) 
6)  SELECT * FROM Users
7)
8)
